spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: techchallenge
  profiles:
    active: ${ENVIRONMENT:local}

server.port: 8080

server:
  error:
    include-stacktrace: never