apiVersion: v1
kind: Service
metadata:
  name: application-svc
  namespace: app
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort # Ou LoadBalancer, se necessário
